<?php


namespace common\widgets;


use common\entities\Word;
use common\repositories\WordRepository;
use yii\base\Widget;
use yii\helpers\Html;

class TranslatableWordWidget extends Widget
{
    /* @var $word Word*/
    public $word;

    /* @var $wordId int*/
    public $wordId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->word) {
            $this->word = \Yii::createObject(WordRepository::class)->getById($this->wordId);
        }
    }

    public function run()
    {
        $word = $this->word->content;

        return Html::tag('div', $word, [
            'class' => 'translatable-word'
        ]);
    }

}