<?php


namespace common\widgets;


use common\entities\Sentence;
use common\repositories\SentenceRepository;
use common\repositories\TextRepository;
use yii\base\Widget;
use yii\helpers\Html;

class TranslatableSentenceWidget extends Widget
{
    /* @var $sentence Sentence*/
    public $sentence;

    /* @var $textId int$*/
    public $sentenceId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if (!$this->sentence) {
            $this->sentence = \Yii::createObject(SentenceRepository::class)->getById($this->sentenceId);
        }
    }

    public function run()
    {
        $sentence = '';

        foreach($this->sentence->words as $word) {
            $sentence .= TranslatableWordWidget::widget([
                'word' => $word
            ]) . ' ';
        }

        return Html::tag('div', $sentence, [
            'class' => 'translatable-sentence'
        ]);
    }
}